# Generated by Django 5.0.6 on 2024-05-25 08:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название сайта')),
                ('desc', ckeditor.fields.RichTextField(verbose_name='Описание сайта')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Логотип сайта')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone', models.PositiveIntegerField(verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Настройка сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
