# Generated by Django 5.0.6 on 2024-05-25 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SettingsModel',
            new_name='Settings',
        ),
    ]
